// Deterministic estimated-T-score regression.
//
// The numeric parameters live in model/model-parameters.ts, generated by the
// NHANES training pipeline. Updating that generated artifact is the only step
// needed to update the deployed scorer; do not duplicate coefficients here.
// The LLM receives this function's fixed output only to explain it.

import { tScoreModel } from "../../model/model-parameters";

export type BoneFeatures = {
  age: number;
  yearsSinceMenopause: number;
  onHormoneTherapy: boolean;
  priorFragilityFracture: boolean;
  bmi: number;
  weightBearingActivity: number;
  currentSmoker: boolean;
  glucocorticoids: boolean;
  rheumatoidArthritis: boolean;
  highAlcohol: boolean;
  vitaminD: number;
  calcium: number;
  // Thyroid disease / CKD "secondary osteoporosis" flag. Only affects the
  // estimate once the model is retrained with it (SECONDARY_CONDITION_TRAINED).
  secondaryCondition: boolean;
};

export const MODEL_IS_VALIDATED = true;

export type FactorContribution = {
  factor: string;
  contribution: number;
  direction: "raises" | "lowers";
};

export type ModelOutput = {
  estimatedTScore: number;
  tScoreRange: [number, number];
  category: "elevated" | "uncertain" | "lower";
  contributions: FactorContribution[];
  validated: boolean;
  mae: number;
};

const round1 = (value: number) => Math.round(value * 10) / 10;
const binary = (value: boolean) => (value ? 1 : 0);

type CoefKey = keyof typeof tScoreModel.coefficients;

export type IntervalConfig = {
  residualStd: number;
  z: number;
  featureVariances: Partial<Record<string, number>>;
  fixedHalfWidth: number;
};

// Per-person prediction-interval half-width. When the training variances have
// been exported, the band widens for each imputed feature by
// coefficient^2 * Var(feature) — the variance discarded by imputing that
// feature's mean — added in quadrature onto the residual variance. With no
// exported variances it falls back to the model's fixed complete-data
// half-width, so behaviour is unchanged until the notebook fills them in.
export function adaptiveHalfWidth(
  imputedFeatures: ReadonlyArray<string>,
  coefficients: Readonly<Record<string, number>>,
  cfg: IntervalConfig,
): number {
  if (!cfg.featureVariances || Object.keys(cfg.featureVariances).length === 0) {
    return cfg.fixedHalfWidth;
  }
  let variance = cfg.residualStd * cfg.residualStd;
  for (const key of imputedFeatures) {
    const v = cfg.featureVariances[key];
    if (typeof v === "number") variance += coefficients[key] * coefficients[key] * v;
  }
  return cfg.z * Math.sqrt(variance);
}

function predictionInterval(
  estimate: number,
  terms: ReadonlyArray<[keyof BoneFeatures, string, number, CoefKey]>,
  provided: Set<keyof BoneFeatures> | null,
  c: typeof tScoreModel.coefficients,
): [number, number] {
  // Without a provided set we cannot tell which inputs were imputed, so use the
  // fixed band. Otherwise every coefficient key whose feature was not supplied
  // is treated as imputed.
  const imputed = provided
    ? terms.filter(([key]) => !provided.has(key)).map(([, , , coefKey]) => coefKey)
    : [];
  const iv = tScoreModel.intervals;
  const halfWidth = provided
    ? adaptiveHalfWidth(imputed, c, {
        residualStd: iv.residualStd,
        z: iv.z,
        featureVariances: iv.featureVariances,
        fixedHalfWidth: tScoreModel.intervalHalfWidth,
      })
    : tScoreModel.intervalHalfWidth;
  return [estimate - halfWidth, estimate + halfWidth];
}

// `providedFeatures`, when given, lists the feature keys the user actually
// supplied. Missing features are still imputed (a linear model has to plug in
// *some* value — the population mean is the neutral choice that adds no
// information above or below baseline; dropping the term is arithmetically
// "impute 0", which for e.g. calcium is nonsense). So the estimate always uses
// all features, but only user-supplied ones are surfaced as "what drove this
// result" — we never present an imputed default as one of her personal factors.
// Omit the argument to show every non-zero factor (legacy behaviour).
export function scoreBone(
  features: BoneFeatures,
  providedFeatures?: ReadonlyArray<keyof BoneFeatures>,
): ModelOutput {
  const c = tScoreModel.coefficients;
  // Each term: [feature key, label, contribution, coefficient key]. The
  // coefficient key links the feature to its coefficient and training variance
  // in model-parameters (note weightBearingActivity uses the activityLevel
  // coefficient).
  const terms: [keyof BoneFeatures, string, number, CoefKey][] = [
    ["age", "Age", c.age * features.age, "age"],
    ["yearsSinceMenopause", "Years since menopause", c.yearsSinceMenopause * features.yearsSinceMenopause, "yearsSinceMenopause"],
    ["onHormoneTherapy", "Hormone therapy", c.onHormoneTherapy * binary(features.onHormoneTherapy), "onHormoneTherapy"],
    ["priorFragilityFracture", "Prior fragility fracture", c.priorFragilityFracture * binary(features.priorFragilityFracture), "priorFragilityFracture"],
    ["bmi", "Body mass index", c.bmi * features.bmi, "bmi"],
    ["weightBearingActivity", "Weight-bearing activity", c.activityLevel * features.weightBearingActivity, "activityLevel"],
    ["currentSmoker", "Current smoker", c.currentSmoker * binary(features.currentSmoker), "currentSmoker"],
    ["glucocorticoids", "Glucocorticoid use", c.glucocorticoids * binary(features.glucocorticoids), "glucocorticoids"],
    ["rheumatoidArthritis", "Rheumatoid arthritis", c.rheumatoidArthritis * binary(features.rheumatoidArthritis), "rheumatoidArthritis"],
    ["highAlcohol", "High alcohol intake", c.highAlcohol * binary(features.highAlcohol), "highAlcohol"],
    ["vitaminD", "Vitamin D", c.vitaminD * features.vitaminD, "vitaminD"],
    ["calcium", "Serum calcium", c.calcium * features.calcium, "calcium"],
    ["secondaryCondition", "Thyroid or chronic kidney disease", c.secondaryCondition * binary(features.secondaryCondition), "secondaryCondition"],
  ];

  const estimate = tScoreModel.intercept + terms.reduce((sum, [, , value]) => sum + value, 0);

  const provided = providedFeatures ? new Set(providedFeatures) : null;
  const [low, high] = predictionInterval(estimate, terms, provided, c);

  // Category from the point estimate against the clinical T-score bands. (The
  // earlier "low <= -2.5" rule over-flagged once the honest 95% band widened to
  // ~+/-1.9; the interval is shown separately as the uncertainty.)
  let category: ModelOutput["category"];
  if (estimate <= -2.5) category = "elevated";
  else if (estimate >= -1.0) category = "lower";
  else category = "uncertain";

  // Show every factor she actually answered, including ~0 contributions --
  // "you told us this and it didn't move your score" is itself informative,
  // and hiding it read as an arbitrary cap. Still excludes anything NOT
  // provided/answered (imputed defaults are never shown as "her" factors).
  const contributions = terms
    .filter(([key]) => !provided || provided.has(key))
    .map(([, factor, contribution]): FactorContribution => ({
      factor,
      contribution,
      direction: contribution > 0 ? "raises" : "lowers",
    }))
    .sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution));

  return {
    estimatedTScore: round1(estimate),
    tScoreRange: [round1(low), round1(high)],
    category,
    contributions,
    validated: MODEL_IS_VALIDATED,
    mae: tScoreModel.mae,
  };
}
