// Deterministic estimated-T-score regression.
//
// The numeric parameters live in model/model-parameters.ts, generated by the
// NHANES training pipeline. Updating that generated artifact is the only step
// needed to update the deployed scorer; do not duplicate coefficients here.
// The LLM receives this function's fixed output only to explain it.

import { tScoreModel } from "../../model/model-parameters";

export type BoneFeatures = {
  age: number;
  yearsSinceMenopause: number;
  onHormoneTherapy: boolean;
  priorFragilityFracture: boolean;
  bmi: number;
  weightBearingActivity: number;
  currentSmoker: boolean;
  parentalHipFracture: boolean;
  glucocorticoids: boolean;
  rheumatoidArthritis: boolean;
  highAlcohol: boolean;
  vitaminD: number;
  calcium: number;
};

export const MODEL_IS_VALIDATED = true;

export type FactorContribution = {
  factor: string;
  contribution: number;
  direction: "raises" | "lowers";
};

export type ModelOutput = {
  estimatedTScore: number;
  tScoreRange: [number, number];
  category: "elevated" | "uncertain" | "lower";
  contributions: FactorContribution[];
  validated: boolean;
};

const round1 = (value: number) => Math.round(value * 10) / 10;
const binary = (value: boolean) => (value ? 1 : 0);

// `providedFeatures`, when given, lists the feature keys the user actually
// supplied. Missing features are still imputed (a linear model has to plug in
// *some* value — the population mean is the neutral choice that adds no
// information above or below baseline; dropping the term is arithmetically
// "impute 0", which for e.g. calcium is nonsense). So the estimate always uses
// all features, but only user-supplied ones are surfaced as "what drove this
// result" — we never present an imputed default as one of her personal factors.
// Omit the argument to show every non-zero factor (legacy behaviour).
export function scoreBone(
  features: BoneFeatures,
  providedFeatures?: ReadonlyArray<keyof BoneFeatures>,
): ModelOutput {
  const c = tScoreModel.coefficients;
  const terms: [keyof BoneFeatures, string, number][] = [
    ["age", "Age", c.age * features.age],
    ["yearsSinceMenopause", "Years since menopause", c.yearsSinceMenopause * features.yearsSinceMenopause],
    ["onHormoneTherapy", "Hormone therapy", c.onHormoneTherapy * binary(features.onHormoneTherapy)],
    ["priorFragilityFracture", "Prior fragility fracture", c.priorFragilityFracture * binary(features.priorFragilityFracture)],
    ["bmi", "Body mass index", c.bmi * features.bmi],
    ["weightBearingActivity", "Weight-bearing activity", c.activityLevel * features.weightBearingActivity],
    ["currentSmoker", "Current smoker", c.currentSmoker * binary(features.currentSmoker)],
    ["parentalHipFracture", "Parental hip fracture", c.parentalHipFracture * binary(features.parentalHipFracture)],
    ["glucocorticoids", "Glucocorticoid use", c.glucocorticoids * binary(features.glucocorticoids)],
    ["rheumatoidArthritis", "Rheumatoid arthritis", c.rheumatoidArthritis * binary(features.rheumatoidArthritis)],
    ["highAlcohol", "High alcohol intake", c.highAlcohol * binary(features.highAlcohol)],
    ["vitaminD", "Vitamin D", c.vitaminD * features.vitaminD],
    ["calcium", "Serum calcium", c.calcium * features.calcium],
  ];

  const estimate = tScoreModel.intercept + terms.reduce((sum, [, , value]) => sum + value, 0);
  const low = estimate - tScoreModel.intervalHalfWidth;
  const high = estimate + tScoreModel.intervalHalfWidth;

  let category: ModelOutput["category"];
  if (estimate <= -2.5 || low <= -2.5) category = "elevated";
  else if (estimate >= -1.0) category = "lower";
  else category = "uncertain";

  const provided = providedFeatures ? new Set(providedFeatures) : null;
  const contributions = terms
    .filter(([key, , value]) => Math.abs(value) > 1e-3 && (!provided || provided.has(key)))
    .map(([, factor, contribution]): FactorContribution => ({
      factor,
      contribution,
      direction: contribution > 0 ? "raises" : "lowers",
    }))
    .sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution));

  return {
    estimatedTScore: round1(estimate),
    tScoreRange: [round1(low), round1(high)],
    category,
    contributions,
    validated: MODEL_IS_VALIDATED,
  };
}
