// Deterministic estimated-T-score regression.
//
// The numeric parameters live in model/model-parameters.ts, generated by the
// NHANES training pipeline. Updating that generated artifact is the only step
// needed to update the deployed scorer; do not duplicate coefficients here.
// The LLM receives this function's fixed output only to explain it.

import { tScoreModel } from "../../model/model-parameters";

export type BoneFeatures = {
  age: number;
  yearsSinceMenopause: number;
  onHormoneTherapy: boolean;
  priorFragilityFracture: boolean;
  bmi: number;
  weightBearingActivity: number;
  currentSmoker: boolean;
  parentalHipFracture: boolean;
  glucocorticoids: boolean;
  rheumatoidArthritis: boolean;
  highAlcohol: boolean;
  vitaminD: number;
  calcium: number;
};

export const MODEL_IS_VALIDATED = true;

export type FactorContribution = {
  factor: string;
  contribution: number;
  direction: "raises" | "lowers";
};

export type ModelOutput = {
  estimatedTScore: number;
  tScoreRange: [number, number];
  category: "elevated" | "uncertain" | "lower";
  contributions: FactorContribution[];
  validated: boolean;
};

const round1 = (value: number) => Math.round(value * 10) / 10;
const binary = (value: boolean) => (value ? 1 : 0);

export function scoreBone(features: BoneFeatures): ModelOutput {
  const c = tScoreModel.coefficients;
  const terms: [string, number][] = [
    ["Age", c.age * features.age],
    ["Years since menopause", c.yearsSinceMenopause * features.yearsSinceMenopause],
    ["Hormone therapy", c.onHormoneTherapy * binary(features.onHormoneTherapy)],
    ["Prior fragility fracture", c.priorFragilityFracture * binary(features.priorFragilityFracture)],
    ["Body mass index", c.bmi * features.bmi],
    ["Weight-bearing activity", c.activityLevel * features.weightBearingActivity],
    ["Current smoker", c.currentSmoker * binary(features.currentSmoker)],
    ["Parental hip fracture", c.parentalHipFracture * binary(features.parentalHipFracture)],
    ["Glucocorticoid use", c.glucocorticoids * binary(features.glucocorticoids)],
    ["Rheumatoid arthritis", c.rheumatoidArthritis * binary(features.rheumatoidArthritis)],
    ["High alcohol intake", c.highAlcohol * binary(features.highAlcohol)],
    ["Vitamin D", c.vitaminD * features.vitaminD],
    ["Serum calcium", c.calcium * features.calcium],
  ];

  const estimate = tScoreModel.intercept + terms.reduce((sum, [, value]) => sum + value, 0);
  const low = estimate - tScoreModel.intervalHalfWidth;
  const high = estimate + tScoreModel.intervalHalfWidth;

  let category: ModelOutput["category"];
  if (estimate <= -2.5 || low <= -2.5) category = "elevated";
  else if (estimate >= -1.0) category = "lower";
  else category = "uncertain";

  const contributions = terms
    .filter(([, value]) => Math.abs(value) > 1e-3)
    .map(([factor, contribution]): FactorContribution => ({
      factor,
      contribution,
      direction: contribution > 0 ? "raises" : "lowers",
    }))
    .sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution));

  return {
    estimatedTScore: round1(estimate),
    tScoreRange: [round1(low), round1(high)],
    category,
    contributions,
    validated: MODEL_IS_VALIDATED,
  };
}
