// The front-gate model is deliberately separate from the T-score regression.
// It estimates whether a full assessment is warranted; it never diagnoses
// osteoporosis and it never sets or alters the eventual T-score.
//
// Parameters are generated by the NHANES training pipeline in
// model/model-parameters.ts. Updating that artifact updates this scorer.

import { triage } from "../../model/model-parameters";

export const TRIAGE_MODEL_IS_VALIDATED = true;
export const TRIAGE_THRESHOLD = triage.threshold;

export type MenopauseStatus = "yes" | "no" | "not-sure";

export type TriageFeatures = {
  age: number;
  bmi?: number;
  menopauseStatus: MenopauseStatus;
};

export type TriageOutput = {
  estimatedProbability: number;
  probabilityPercent: number;
  thresholdPercent: number;
  proceedToFullAssessment: boolean;
  validated: boolean;
  usedDefaultBmi: boolean;
};

const sigmoid = (value: number) => 1 / (1 + Math.exp(-value));
const round1 = (value: number) => Math.round(value * 10) / 10;

export function scoreTriage(features: TriageFeatures): TriageOutput {
  const usedDefaultBmi = features.bmi === undefined;
  const bmi = features.bmi ?? triage.bmiMedian;
  const postmenopausal = features.menopauseStatus === "yes" ? 1 : 0;
  const probability = sigmoid(
    triage.intercept +
      triage.coefficients.age * features.age +
      triage.coefficients.bmi * bmi +
      triage.coefficients.postmenopausal * postmenopausal,
  );

  return {
    estimatedProbability: probability,
    probabilityPercent: round1(probability * 100),
    thresholdPercent: TRIAGE_THRESHOLD * 100,
    proceedToFullAssessment: probability > TRIAGE_THRESHOLD,
    validated: TRIAGE_MODEL_IS_VALIDATED,
    usedDefaultBmi,
  };
}
